services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ./.docker/local-dev.sh
    container_name: nogain-dev-api
    ports:
      - '5000:5000'
    volumes:
      - .:/home/node/app
      
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:18-alpine
    # build: .docker/postgres
    container_name: nogain-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql
    ports:
    - "5432:5432"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: nogain-otel-collector
    command: ["--config", "/etc/otel-config.yaml"]
    ports:
      - "4318:4318" # OTLP Http (metrics/traces)
      - "55681:55681" # OTLP gRpc (trace)
      - "8888:8888" # Heath check
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: nogain-jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector endpoint
    