on:
  pull_request:
    branches:
      - develop



jobs:
  server-format-check:
    name: Format Check
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          # cache: 'npm'
          package-manager-cache: false
          # cache-dependency-path: server/package-lock.json

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - run: pnpm install 
      - run: pnpm run format:ci


  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          
          package-manager-cache: false

      - uses: pnpm/action-setup@v4
        with: 
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test
